- name: Install Nginx on webservers 1 2 3
  hosts: pvt
  gather_facts: yes
  become: yes
  become_user: root
  vars:
   nginx_port: 80
   version: 1.0.0
   t_version: 1.9.8
  tasks:
  - name: Check nginx status
    shell: nginx -v
    register: nginx_status_output
    ignore_errors: yes
    tags: [check]

  - name: Perform Apt update
    shell: apt update
    when: nginx_status_output.rc !=0

  - name: Install nginx webserver
    shell: apt install -y nginx
    tags:
    - nginx_install
    - install_nginx
  - name: Start nginx webserver
    shell: service nginx start 
    when: nginx_status_output.rc !=0
    tags: [service_install, install_service]
  tags:
  - nginx  
- name: InstallSupport tools
  hosts: pub
  become: yes
  become_user: root
  tasks:
  - name: InstallSupport tools
    shell: apt install -y net-tools jq tree unzip
    tags:
    - tools_install
  tags:
  - tools